Feat/declarative ddl
wesql/wescale pull request #560
Opened 2024-10-24 05:49 UTC by newborn22

## Related Issue(s) & Descriptions

## Checklist

-   [ ] Tests were added or are not required
-   [ ] Documentation was added or is not required

2024-10-31 16:48 UTC, earayu commented
What will happen if it's a temporary table?

2024-10-31 16:54 UTC, earayu commented
Need to add testcase for `declarative_ddl.go`

2024-10-31 17:03 UTC, earayu requested changes

2024-11-01 02:01 UTC, newborn22 commented
> What will happen if it's a temporary table? @newborn22

```
if ddl.CreateTempTable {
	vcursor.Session().HasCreatedTempTable()
	vcursor.Session().NeedsReservedConn()
	return vcursor.ExecutePrimitive(ctx, ddl.NormalDDL, bindVars, wantfields)
}
```
declarative ddl will be executed:
1. It's a create table statement and the table is not temporary.
2. @@enable_declarative_ddl is set ture.

2024-11-01 02:26 UTC, newborn22 commented on go/vt/vtgate/engine/declarative_ddl.go
> +}
column set to be primary key should be set not null too in createTableStmt, otherwise it will lead some bugs such as it will output an diff ddl even you input same create table sql more than once.

2024-11-01 02:28 UTC, newborn22 commented on go/vt/vtgate/engine/declarative_ddl.go
> +}
`normalizeCreateTableStmt` is used to deal with such cases mentioned above.

2024-11-01 04:05 UTC, newborn22 commented on go/vt/vtgate/engine/declarative_ddl.go
> +		uuid := qr.Named().Rows[0].AsString("uuid", "")
fixed by merging multiple results into one.

2024-11-02 06:08 UTC, earayu approved these changes

2024-11-02 08:25 UTC, merged

2024-11-02 08:25 UTC, newborn22 commented
/pick-and-release 0.3 0.3.5

2024-11-02 08:27 UTC, newborn22 commented
/pick-and-release release-0.3 0.3.5